### ISSUE TITLE
Adding line depends=TimerOne makes library incompatible with platformio-esp32-arduindo config.

### ISSUE THREAD

**Issue by bleep1** [adafruit/LPD8806#31]
Had problems with this line using this library in PlatformIO
https://github.com/adafruit/LPD8806/blob/a22f8ca24878f2c118a063e90ba00124e28ee304/library.properties#L10

depends=TimerOne

My project platformio.ini config:
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

It seems that TimerOne doesn't compile in this config. I dropped back to 1.0.1 without this line and all is good. 
Just FYI
Bleep,

**Comment by ladyada** [comment]
hi this is definitely a dependancy for arduin you can disable library install/compilation within platformio
